DB:
  Host: 'www.captainnas.com'
  Port: '23306'
  DBname: 'DemoServerDB'
  username: 'admin'
  password: 'admin'

Jenkins:
  Host: 'www.captainnas.com'
  Port: '28080'
  username: 'admin'
  password: '110510b6c9f4b6ad083384608a0c3a3be9'
  securitytoken: